CREATE TABLE plant_dex_plant_info (
    id Integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nickName TEXT NOT NULL,
    scientificName TEXT NOT NULL,
    datePurchased DATE NOT NULL,
    purchasePlace TEXT NOT NULL,
    user_id INTEGER
        REFERENCES plant_dex_users(id) ON DELETE CASCADE NOT NULL

);